### PR TITLE
CI

### PR DESCRIPTION
**Pull request by sphamba**
# Prework

- [x] I understand and agree to this repository's [code of conduct](https://github.com/ghiggi/gpm_api/blob/main/CODE_OF_CONDUCT.md).
- [x] I understand and agree to this repository's [contributing guidelines](https://github.com/ghiggi/gpm_api/blob/main/CONTRIBUTING.md).
- [ ] I have already submitted an [issue](https://github.com/ghiggi/gpm_api/issues) or [discussion thread](https://github.com/ghiggi/gpm_api/discussions) to discuss my idea with the maintainers.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Documentation
- [ ] Tutorial
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and communicate accordingly:

**The PR fulfills these requirements:**

- [x] It's submitted to the branch named as follow :
  - Fix a bug: `bugfix-<some_key>-<word>`
  - Improve the doc: `doc-<some_key>-<word>`
  - Improve a tutorial `tutorial-<some_key>-<word>`
  - Add a new feature: `feature-<some_key>-<word>`
  - Refactor some code: `refactor-<some_key>-<word>`
  - Optimize some code: `optimize-<some_key>-<word>`
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] Don't forget to link PR to issue if you are solving one.
- [ ] All tests are passing.
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

# Related GitHub issues and pull requests

- Ref: #

# Summary

- Run tests on multiple python versions
- Run tests on latest packages
- Run pre-commits on CI and locally
- Documentation compilation

*Where @ghiggi action is required on original repo:*
- [x] Register coverage and code checks services
- [x] Create Readthedocs entry (eventually give mod rights to @sphamba)

*Notes*
For the moment, the doc source files generated from the code are created by manually running a command, and they are version controlled. It might be worth having them generated automatically by RTD and not pushed on git imo.

### CODE REVIEW

**Comment by ghiggi** [comment]
I added the tokens for CodeCov and CoverAlls to gpm_api, ximage and pycolorbar repositories.
You might want to update the CI with this code snippets:
```
- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v3
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```
```
- name: Coveralls GitHub Action
  uses: coverallsapp/github-action@v2
```
I also added the GitHub Apps CodeCov, pre-commit.ci, CoverAlls Official, CodeFactor and CodeScene to all directories.

**Comment by sphamba** [comment]
CI and documentation build are running!

**Comment by ghiggi** [comment]
@sphamba @regislon @ evanjt I already sent you collaborator invitations. Once accepted, I can gives you roles ...

**Review by evanjt — APPROVED** [review]

**Comment by regislon** [comment]
@sphamba @ghiggi @evanjt I'm just jumping in on this PR. I'm not sure if it's relevant, but I don't think there's a need to duplicate the requirements in requirements.txt. Readthedocs can also be based on the pyproject.toml. Check the [enac-it4r-repo-python](https://github.com/EPFL-ENAC/enac-it4r-repo-python) and https://github.com/sphinx-toolbox/sphinx-pyproject

**Comment by sphamba** [comment]
> I'm just jumping in on this PR. I'm not sure if it's relevant, but I don't think there's a need to duplicate the requirements in requirements.txt. Readthedocs can also be based on the pyproject.toml. Check the [enac-it4r-repo-python](https://github.com/EPFL-ENAC/enac-it4r-repo-python) and https://github.com/sphinx-toolbox/sphinx-pyproject

Nice I didn't know that! I tweaked the doc generation config

**Pull request merged**
